from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
WORKBOOK = next((ROOT / "data").glob("*.xlsx"))
OUTPUT = ROOT / "src" / "domain" / "workbook.generated.ts"
DOCS = ROOT / "docs" / "workbook-map.md"


def normalize_formula(value: str) -> str:
    formula = value.replace("_xlfn.", "")
    formula = formula.replace("Спринт!", "'Спринт'!")
    formula = re.sub(r"(?<![A-ZА-Яа-я0-9_])TRUE(?![A-ZА-Яа-я0-9_(])", "TRUE()", formula)
    formula = re.sub(r"(?<![A-ZА-Яа-я0-9_])FALSE(?![A-ZА-Яа-я0-9_(])", "FALSE()", formula)
    return formula


def cell_value(cell: Any) -> Any:
    value = cell.value
    if isinstance(value, str) and value.startswith("="):
        return normalize_formula(value)
    return value


def trim_row(row: list[Any]) -> list[Any]:
    last = len(row)
    while last and row[last - 1] is None:
        last -= 1
    return row[:last]


def main() -> None:
    workbook = openpyxl.load_workbook(WORKBOOK, data_only=False)
    sheets: dict[str, list[list[Any]]] = {}
    dimensions: dict[str, dict[str, int]] = {}
    formula_count = 0

    for sheet in workbook.worksheets:
        rows: list[list[Any]] = []
        for row in sheet.iter_rows(
            min_row=1,
            max_row=sheet.max_row,
            min_col=1,
            max_col=sheet.max_column,
        ):
            values = [cell_value(cell) for cell in row]
            formula_count += sum(
                1 for item in values if isinstance(item, str) and item.startswith("=")
            )
            rows.append(trim_row(values))
        sheets[sheet.title] = rows
        dimensions[sheet.title] = {
            "rows": sheet.max_row,
            "columns": sheet.max_column,
            "formulas": sum(
                1
                for row in rows
                for item in row
                if isinstance(item, str) and item.startswith("=")
            ),
        }

    payload = {
        "sourceFile": WORKBOOK.name,
        "generatedAt": "generated locally",
        "sheets": sheets,
        "dimensions": dimensions,
        "formulaCount": formula_count,
    }

    OUTPUT.write_text(
        "// Generated by frontend/scripts/extract_workbook.py. Do not edit by hand.\n"
        "import type { WorkbookSnapshot } from './workbookTypes';\n\n"
        f"export const workbookSnapshot = {json.dumps(payload, ensure_ascii=False, indent=2)} as const satisfies WorkbookSnapshot;\n",
        encoding="utf-8",
    )

    DOCS.write_text(
        "# Карта Excel-калькулятора\n\n"
        f"Источник: `{WORKBOOK.name}`\n\n"
        "## Листы\n\n"
        + "\n".join(
            f"- `{name}`: {meta['rows']} строк, {meta['columns']} колонок, {meta['formulas']} формул"
            for name, meta in dimensions.items()
        )
        + "\n\n## Основные входы\n\n"
        "- `D33` количество пролётов.\n"
        "- `B35`, `D35`, `F35`, `H35`, `J35` ширина пролётов.\n"
        "- `B38` длина здания, `B40` шаг рам, `F43` высота.\n"
        "- `AM4:AM70` скрытые параметры проекта: база, страна, сейсмика, КМ/АС, кровля, перекрытия, антресоли, краны, лестницы, ограждения, перегородки и прочие опции.\n"
        "- `W51`, `W53`, `W61`, `W63` количества и типы окон/дверей.\n"
        "- `B46:J46`, `L46`, `B50:L58` размеры перекрытий и антресолей.\n"
        "- `F71:F77`, `N71:N77` количества лестниц.\n"
        "- `B81`, `B85`, `B88`, `M81` площади и проёмы перегородок.\n\n"
        "## Основные выходы\n\n"
        "- `Z9` стоимость проектных работ КМ, тыс. руб.\n"
        "- `Z10` срок проектирования КМ, рабочих дней.\n"
        "- `Z15:Z20` стоимость проектных работ по конструктивам, тыс. руб/т.\n"
        "- `AO79:BF80` и `BL79:CC80` скрытые матрицы стоимости и сроков по вариантам.\n\n"
        "## Нормализация формул\n\n"
        "- `_xlfn.CEILING.MATH` преобразуется в `CEILING.MATH`.\n"
        "- Ссылки `Спринт!` преобразуются в `'Спринт'!`, чтобы формульный движок корректно разбирал кириллическое имя листа.\n",
        encoding="utf-8",
    )

    print(f"Generated {OUTPUT.relative_to(ROOT)} from {WORKBOOK.name}")


if __name__ == "__main__":
    main()
